# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Lint and build
on:
  push:
    branches:
      - main
      - master
    paths:
      - '**.py'
      - '**.pyi'
      - '**.ui'
  pull_request:
    branches:
      - main
      - master
      - dev
      - dev*
      - 2.0.0
    paths:
      - '**.py'
      - '**.pyi'
      - '**.ui'
jobs:
  Pyright:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'scripts/requirements-dev.txt'
      - name: Install dependencies
        run: |
          pip install -r "scripts/requirements-dev.txt"
          npm install -g pyright
          npm list -g pyright
      - run: scripts/compile_resources.ps1
      - name: Analysing the code with Pyright
        run: pyright --warnings
  Pylint:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'scripts/requirements-dev.txt'
      - name: Install dependencies
        run: pip install -r "scripts/requirements-dev.txt"
      - run: scripts/compile_resources.ps1
      - name: Analysing the code with Pylint
        run: pylint --reports=y --output-format=colorized src/
  Flake8:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'scripts/requirements-dev.txt'
      - name: Install dependencies
        run: pip install -r "scripts/requirements-dev.txt"
      - run: scripts/compile_resources.ps1
      - name: Analysing the code with Flake8
        run: flake8
  Bandit:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'scripts/requirements-dev.txt'
      - name: Install dependencies
        run: pip install -r "scripts/requirements-dev.txt"
      - run: scripts/compile_resources.ps1
      - name: Analysing the code with Bandit
        run: bandit -n 1 --severity-level medium --recursive src
  Build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r "scripts/requirements.txt"
      - run: scripts/build.ps1
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AutoSplit (Python ${{ matrix.python-version }})
          path: dist/AutoSplit.exe
